#!/usr/bin/env tsx
/**
 * TypeScript Type Generator from OpenAPI Spec
 * 
 * Generates TypeScript types from the OpenAPI specification.
 * This ensures type safety between API contract and TypeScript code.
 * 
 * Usage: tsx src/openapi/generate-types.ts
 */

import { readFileSync, writeFileSync } from "fs";
import { join } from "path";
import { fileURLToPath } from "url";
import { dirname } from "path";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

interface OpenAPISpec {
  components: {
    schemas: Record<string, any>;
  };
}

function toTypeScriptType(schema: any, name: string, schemas: Record<string, any>): string {
  if (schema.$ref) {
    const refName = schema.$ref.split("/").pop()!;
    return refName;
  }

  if (schema.type === "object") {
    if (!schema.properties) {
      return "Record<string, unknown>";
    }

    const props = Object.entries(schema.properties as Record<string, any>)
      .map(([propName, propSchema]: [string, any]) => {
        const isRequired = schema.required?.includes(propName) ?? false;
        const optional = isRequired ? "" : "?";
        const type = toTypeScriptType(propSchema, propName, schemas);
        return `  ${propName}${optional}: ${type};`;
      })
      .join("\n");

    return `{\n${props}\n}`;
  }

  if (schema.type === "array") {
    const itemType = toTypeScriptType(schema.items, `${name}Item`, schemas);
    return `${itemType}[]`;
  }

  if (schema.enum) {
    return schema.enum.map((v: string) => `"${v}"`).join(" | ");
  }

  switch (schema.type) {
    case "string":
      if (schema.format === "date-time") {
        return "string"; // ISO 8601 string
      }
      return "string";
    case "number":
    case "integer":
      return "number";
    case "boolean":
      return "boolean";
    case "null":
      return "null";
    default:
      return "unknown";
  }
}

function generateTypes(spec: OpenAPISpec): string {
  const schemas = spec.components.schemas;
  const typeDefinitions: string[] = [];

  typeDefinitions.push("// Auto-generated TypeScript types from OpenAPI spec");
  typeDefinitions.push("// DO NOT EDIT MANUALLY - Generated by generate-types.ts");
  typeDefinitions.push("// Last generated: " + new Date().toISOString());
  typeDefinitions.push("");

  // Generate types for each schema
  for (const [schemaName, schema] of Object.entries(schemas)) {
    if (schemaName === "ErrorResponse") {
      typeDefinitions.push(`export interface ${schemaName} {`);
      typeDefinitions.push("  error: string;");
      typeDefinitions.push("  code?: string;");
      typeDefinitions.push("  details?: Record<string, unknown>;");
      typeDefinitions.push("}");
      typeDefinitions.push("");
      continue;
    }

    const type = toTypeScriptType(schema, schemaName, schemas);
    
    if (type.includes("\n")) {
      // Multi-line type (object)
      typeDefinitions.push(`export type ${schemaName} = ${type};`);
    } else {
      // Single-line type
      typeDefinitions.push(`export type ${schemaName} = ${type};`);
    }
    typeDefinitions.push("");
  }

  // Generate request/response types for each endpoint
  typeDefinitions.push("// Request/Response Types");
  typeDefinitions.push("");

  typeDefinitions.push("export interface CreateIntentRequest {");
  typeDefinitions.push("  railsType: 'ACH' | 'WIRE';");
  typeDefinitions.push("  amountMinor: string;");
  typeDefinitions.push("  currency?: string;");
  typeDefinitions.push("  beneficiaryId: string;");
  typeDefinitions.push("  purpose: string;");
  typeDefinitions.push("}");
  typeDefinitions.push("");

  typeDefinitions.push("export interface UpdateIntentRequest {");
  typeDefinitions.push("  beneficiaryId?: string;");
  typeDefinitions.push("  purpose?: string;");
  typeDefinitions.push("  amountMinor?: string;");
  typeDefinitions.push("  railsType?: 'ACH' | 'WIRE';");
  typeDefinitions.push("}");
  typeDefinitions.push("");

  typeDefinitions.push("export interface CreateChallengeRequest {");
  typeDefinitions.push("  language?: 'EN' | 'ES';");
  typeDefinitions.push("}");
  typeDefinitions.push("");

  typeDefinitions.push("export interface SubmitProofRequest {");
  typeDefinitions.push("  channel?: 'BROWSER' | 'PHONE';");
  typeDefinitions.push("  transcript: string;");
  typeDefinitions.push("  transcriptLanguage?: string | null;");
  typeDefinitions.push("  deviceMetadataJson?: Record<string, unknown>;");
  typeDefinitions.push("}");
  typeDefinitions.push("");

  typeDefinitions.push("export interface CreateDecisionRequest {");
  typeDefinitions.push("  action: 'APPROVE' | 'DENY' | 'STEP_UP';");
  typeDefinitions.push("  proofId: string;");
  typeDefinitions.push("  reasonCodesJson?: string[];");
  typeDefinitions.push("}");
  typeDefinitions.push("");

  typeDefinitions.push("export interface CreateBeneficiaryRequest {");
  typeDefinitions.push("  displayName: string;");
  typeDefinitions.push("  country: string;");
  typeDefinitions.push("  railsAllowed: ('ACH' | 'WIRE')[];");
  typeDefinitions.push("  bankLast4: string;");
  typeDefinitions.push("  bankTokenHash: string;");
  typeDefinitions.push("}");
  typeDefinitions.push("");

  typeDefinitions.push("export interface UpdateBeneficiaryRequest {");
  typeDefinitions.push("  displayName?: string;");
  typeDefinitions.push("  country?: string;");
  typeDefinitions.push("  railsAllowed?: ('ACH' | 'WIRE')[];");
  typeDefinitions.push("  bankLast4?: string;");
  typeDefinitions.push("  bankTokenHash?: string;");
  typeDefinitions.push("  status?: 'ACTIVE' | 'LOCKED' | 'PENDING_VERIFICATION';");
  typeDefinitions.push("}");
  typeDefinitions.push("");

  typeDefinitions.push("export interface CreatePolicyRequest {");
  typeDefinitions.push("  policyId?: string;");
  typeDefinitions.push("  thresholds: PolicyThresholds;");
  typeDefinitions.push("  rules: PolicyRules;");
  typeDefinitions.push("}");
  typeDefinitions.push("");

  typeDefinitions.push("export interface SimulatePolicyRequest {");
  typeDefinitions.push("  railsType: 'ACH' | 'WIRE';");
  typeDefinitions.push("  amountMinor: string;");
  typeDefinitions.push("  beneficiaryId: string;");
  typeDefinitions.push("}");
  typeDefinitions.push("");

  return typeDefinitions.join("\n");
}

function main() {
  const specPath = join(__dirname, "wire.openapi.json");
  const outputPath = join(__dirname, "..", "types", "api-generated.ts");

  console.log(`Generating TypeScript types from: ${specPath}`);
  console.log(`Output: ${outputPath}\n`);

  let spec: OpenAPISpec;
  try {
    const specContent = readFileSync(specPath, "utf-8");
    spec = JSON.parse(specContent);
  } catch (error: any) {
    console.error(`❌ Failed to read/parse OpenAPI spec: ${error.message}`);
    process.exit(1);
  }

  const types = generateTypes(spec);

  try {
    writeFileSync(outputPath, types, "utf-8");
    console.log("✅ TypeScript types generated successfully!");
    console.log(`   Generated ${Object.keys(spec.components.schemas).length} types`);
  } catch (error: any) {
    console.error(`❌ Failed to write types: ${error.message}`);
    process.exit(1);
  }
}

main();
